package mapreduce

import (
	"encoding/json"
	"fmt"
	"hash/fnv"
	"io/ioutil"
	"log"
	"os"
)

func doMap(
	jobName string, // the name of the MapReduce job1
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue,
) {
	//
	// doMap manages one map task: it should read one of the input files
	// (inFile), call the user-defined map function (mapF) for that file's
	// contents, and partition mapF's output into nReduce intermediate files.
	//
	// There is one intermediate file per reduce task. The file name
	// includes both the map task number and the reduce task number. Use
	// the filename generated by reduceName(jobName, mapTask, r)
	// as the intermediate file for reduce task r. Call ihash() (see
	// below) on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	/**
	KeyValue{key string, value string}
	*/
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
	// Your code here (Part I).
	//
	/**
	** the type of buf is []byte
	**/
	bytes, err := ioutil.ReadFile(inFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "File Error: %s\n", err)
		//log.Fatal("Unable to read file: ", inFile)
	}
	inFileContents := string(bytes)
	//The return of function mapF is []KeyValue
	kvpairs := mapF(inFile, inFileContents)

	encoders := make([]*json.Encoder, nReduce)
	for reduceTaskIdx := 0; reduceTaskIdx < nReduce; reduceTaskIdx++ {
		reduceFileName := reduceName(jobName, mapTask, reduceTaskIdx)
		reduceFile, err := os.Create(reduceFileName)
		if err != nil {
			log.Fatal("Unable to create file: ", err)
		}
		defer reduceFile.Close()
		encoders[reduceTaskIdx] = json.NewEncoder(reduceFile)
	}

	for _, kv := range kvpairs {
		idx := ihash(kv.Key) % nReduce
		err := encoders[idx].Encode(&kv)
		if err != nil {
			log.Fatal("Unable to encode: ", err)
		}
	}
	/*
		for i := 0; i < nReduce; i++ {
			reducefileName := reduceName(jobName, mapTask, i)
			outputFile, outputErr := os.OpenFile(reducefileName, os.O_WRONLY|os.O_CREATE, 0666)
			if outputErr != nil {
				fmt.Fprintf(os.Stderr, "File Error: %s\n", err)
			}
			defer outputFile.Close()
			enc := json.NewEncoder(outputFile)
			for _, kv := range mapFOutput {
				if ihash(kv.Key)%nReduce == i {
					err := enc.Encode(&kv)
					if err != nil {
						log.Fatal("doMap: encode error: ", err)
					}
				}
			}
		}*/
	/*
		for _, kv := range mapFOutput {
			//hashtemp
			hashtemp := ihash(kv.Key)
			reducefileName := reduceName(jobName, mapTask, hashtemp%nReduce)
			//打开文件
			outputFile, outputErr := os.OpenFile(reducefileName, os.O_WRONLY|os.O_CREATE, 0666)
			if outputErr != nil {
				fmt.Fprintf(os.Stderr, "File Error: %s\n", err)
			}
			defer outputFile.Close()

			enc := json.NewEncoder(outputFile)
			err := enc.Encode(kv)
			if err != nil {
				log.Println("Error in encodeing json")
			}
		}*/
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
